# 1. Configurações Globais e Schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'magical_palette'

# 2. Definição do Formato Visual (Prompt)
format = """
[](color_pink_bold)\
$os\
[](bg:color_peach fg:color_pink_bold)\
$directory\
[](fg:color_peach bg:color_purple)\
$git_branch\
$git_status\
[](fg:color_purple bg:color_teal)\
$rust\
$python\
$golang\
$nodejs\
[](fg:color_teal bg:color_deep_wine)\
$docker_context\
$conda\
$pixi\
[](fg:color_deep_wine bg:color_dark_purple)\
$time\
[ ](fg:color_dark_purple)\
$cmd_duration\
$line_break$character""" 

# 3. Paleta de Cores
[palettes.magical_palette]
color_light_pink  = '#fde6ee'
color_peach       = '#f6cdcb'
color_pink_bold   = '#ff3e8b'
color_purple      = '#ae72d4'
color_teal        = '#527e81'
color_deep_wine   = '#76445f'
color_dark_purple = '#47324E'
color_yellow      = '#fbbf2d'

# 4. Configuração de Sistema e Usuário
[os]
disabled = false
style = "bg:color_pink_bold fg:color_light_pink"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Fedora = "󰣛 "
Gentoo = "󰣨 "
Linux = "󰌽 "
Macos = "󰀵 "
Manjaro = " "
Mint = "󰣭 "
NixOS = " "
Raspbian = "󰐿 "
RedHatEnterprise = "󱄛 "
Redhat = "󱄛 "
SUSE = " "
Ubuntu = "󰕈 "
Windows = " "

[username]
show_always = true
style_user = "bg:color_pink_bold fg:color_light_pink"
style_root = "bg:color_pink_bold fg:color_light_pink"
format = '[ $user ]($style)'

# 5. Navegação e Diretório
[directory]
style = "fg:color_pink_bold bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

# 6. Git e Controle de Versão
[git_branch]
symbol = ""
style = "bg:color_purple"
format = '[[ $symbol $branch ](fg:color_light_pink bg:color_purple)]($style)'

[git_status]
style = "bg:color_purple"
format = '[[($all_status$ahead_behind )](fg:color_light_pink bg:color_purple)]($style)'

# 7. Linguagens e Ambientes (Cerceta)
[rust]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

[python]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

[golang]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

[nodejs]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_peach bg:color_teal)]($style)'

# 8. Containers e Ambientes Virtuais (Vinho)
[docker_context]
symbol = " "
style = "bg:color_deep_wine"
format = '[[ $symbol( $context) ](fg:color_light_pink bg:color_deep_wine)]($style)'

[conda]
symbol = " "
style = "fg:color_light_pink bg:color_deep_wine"
format = '[$symbol$environment ]($style)'
ignore_base = false

[pixi]
symbol = "󰘦 "
style = "fg:color_light_pink bg:color_deep_wine"
format = '[$symbol$environment ]($style)'

# 9. Utilidades, Duração e Tempo
[time]
disabled = false
time_format = "%R"
style = "bg:color_dark_purple"
format = '[[ $time ](fg:color_light_pink bg:color_dark_purple)]($style)'

[cmd_duration]
show_milliseconds = true
format = "  $duration " 
style = "fg:color_dark_purple"
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:color_pink_bold)' 
error_symbol   = '[](bold fg:color_yellow)'
vimcmd_symbol  = '[](bold fg:color_light_pink)'
